### ISSUE TITLE
TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by ccharlton** [mikestead/lighthouse-batch#4]
Using v2.1.0:
`
/usr/local/lib/node_modules/lighthouse-batch/index.js:107
  const total = report.reportCategories.reduce((sum, cat) => sum + cat.score, 0)
                                        ^

TypeError: Cannot read property 'reduce' of undefined
    at getAverageScore (/usr/local/lib/node_modules/lighthouse-batch/index.js:107:41)
    at updateSummary (/usr/local/lib/node_modules/lighthouse-batch/index.js:102:19)
    at sitesInfo.map (/usr/local/lib/node_modules/lighthouse-batch/index.js:41:21)
    at Array.map (<anonymous>)
    at execute (/usr/local/lib/node_modules/lighthouse-batch/index.js:27:38)
    at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse-batch/run.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
`

**Comment by mikestead** [comment]
@ccharlton Sorry about that. I've just cut `v3` which should have fixed this and provides the latest lighthouse support. Let me know if you run into any more issues.
