### ISSUE TITLE
 ReferenceError: URL is not defined when lighthouse-batch runs as cron job

### ISSUE THREAD

**Issue by Peitemoukiemena** [mikestead/lighthouse-batch#46]
I am running this command 
```
/usr/local/bin/lighthouse-batch -s "https://1.site","https://2.site","https://3.site",
"https://4.site" --html --out /var/www/lighthouse/`date +"%F"`/
```
It works fine. 
I added this command in a bash script. I run the script, still works fine. 

Then I run the script as a cron job, I get the following error. 
```
"/usr/local/lib/node_modules/lighthouse-batch/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36
class URLShim extends URL {
                          ^
                          
            ReferenceError: URL is not defined
            at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse-batch/node_modules/lighthouse/lighthouse-core/lib/url-shim.js:36:23)
            at Module._compile (module.js:652:30)
            at Object.Module._extensions..js (module.js:663:10)
            at Module.load (module.js:565:32)
            at tryModuleLoad (module.js:505:12)
            at Function.Module._load (module.js:497:3)
            at Module.require (module.js:596:17)
            at require (internal/module.js:11:18)
            at Object.<anonymous> (/usr/local/lib/node_modules/lighthouse-batch/node_modules/lighthouse/lighthouse-core/lib/network-request.js:14:13)
            at Module._compile (module.js:652:30)
            "
```
```
node --version
v12.18.3
```
Is there maybe a variable I need to set in cron? Or in the script?

**Comment by Peitemoukiemena** [comment]
This is not an issue with the code. 
From my terminal 
```
 which node
/usr/local/bin/node
```
but from cron it's `/usr/bin/node`.
```
~$ /usr/bin/node --version
v8.10.0
~$ /usr/local/bin/node --version
v12.18.3
```
 I don't know how I could have removed or upgraded the `/usr/bin/node` old version, so I did the following. 
```
sudo mv /usr/bin/node /usr/bin/node.old
sudo ln -s /usr/local/bin/node /usr/bin/node
```
and my command worked from the cron job.

**Comment by mikestead** [comment]
Hey @Peitemoukiemena thanks for the details. 

As you discovered via your fix, this looks like an older issue from lighthouse regarding target node version https://github.com/GoogleChrome/lighthouse/issues/8909 

Going to close this as it looks resolved
